### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by seanohue** [seanohue/vue-howler-bus#7]
Good to have directions on how to contribute

**Comment by Rakteem007** [comment]
can i contribute to this issue?

**Comment by seanohue** [comment]
@Rakteem007 feel free to submit a PR adding a document similar to https://github.com/torus-online/torus/blob/master/CONTRIBUTING.MD as they have a high quality contributing guide, just change the names/links where appropriate and add a note that the document is adapted from Torus.

**Comment by Rakteem007** [comment]
> @Rakteem007 feel free to submit a PR adding a document similar to https://github.com/torus-online/torus/blob/master/CONTRIBUTING.MD as they have a high quality contributing guide, just change the names/links where appropriate and add a note that the document is adapted from Torus.

okk @seanohue

**Comment by seanohue** [comment]
Closed by #11  -- thank you @Rakteem007
